build: false
clone_folder: C:\projects\cakephp-database-backup
max_jobs: 3
platform: x86

environment:
  global:
    PHP: "C:/PHP"

services:
  - mysql
  - postgresql95

init:
  - SET PATH=C:\php\;%PATH%

install:
  - cd c:\
  - appveyor DownloadFile http://windows.php.net/downloads/releases/php-5.6.32-nts-Win32-VC11-x86.zip -FileName php.zip
  - 7z x php.zip -oc:\php > nul
  - cd c:\php
  - copy php.ini-production php.ini

  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_sqlsrv_56_nts.dll >> php.ini
  - echo extension=php_pdo_sqlsrv_56_nts.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_mysql.dll >> php.ini
  - cd C:\projects\cakephp-database-backup
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist --no-interaction --ansi --no-progress
  - php -i | grep "ICU version"

test_script:
  - cd C:\projects\cakephp-database-backup
  - vendor\bin\phpunit.bat
