build: false
clone_folder: C:\projects\cakephp-database-backup
max_jobs: 3
platform: x86

environment:
  global:
    PHP: "C:/PHP"

  matrix:
    - db: mysql
      db_dsn: 'mysql://root:Password12!@localhost/test'

services:
  - mysql
  - postgresql

init:
  - SET PATH=C:\php\;%PATH%

before_test:
  - SET PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% create test

install:
  - cd c:\
  - appveyor DownloadFile http://windows.php.net/downloads/releases/php-5.6.33-nts-Win32-VC11-x86.zip -FileName php.zip
  - 7z x php.zip -oc:\php > nul
  - cd c:\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - cd C:\projects\cakephp-database-backup
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist --no-interaction --ansi --no-progress
  - php -i | grep "ICU version"

test_script:
  - cd C:\projects\cakephp-database-backup
  - vendor\bin\phpunit.bat
